export const chatConstants = {
    // Get Conversations
    FETCH_CONVERSATIONS_REQUEST: 'FETCH_CONVERSATIONS_REQUEST',
    FETCH_CONVERSATIONS_SUCCESS: 'FETCH_CONVERSATIONS_SUCCESS',
    FETCH_CONVERSATIONS_FAILURE: 'FETCH_CONVERSATIONS_FAILURE',
};