export const postsConstants = {
    FETCH_POSTS_REQUEST: 'FETCH_POSTS_REQUEST',
    FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
    FETCH_POSTS_FAILURE: 'FETCH_POSTS_FAILURE',
    // Create Post
    CREATE_POST_REQUEST: 'CREATE_POST_REQUEST',
    CREATE_POST_SUCCESS: 'CREATE_POST_SUCCESS',
    CREATE_POST_FAILURE: 'CREATE_POST_FAILURE',
    // User Posts
    FETCH_USER_POSTS_REQUEST: 'FETCH_USER_POSTS_REQUEST',
    FETCH_USER_POSTS_SUCCESS: 'FETCH_USER_POSTS_SUCCESS',
    FETCH_USER_POSTS_FAILURE: 'FETCH_USER_POSTS_FAILURE',
    // Update Post
    UPDATE_POST_REQUEST: 'UPDATE_POST_REQUEST',
    UPDATE_POST_SUCCESS: 'UPDATE_POST_SUCCESS',
    UPDATE_POST_FAILURE: 'UPDATE_POST_FAILURE',
    // Delete Post
    DELETE_POST_REQUEST: 'DELETE_POST_REQUEST',
    DELETE_POST_SUCCESS: 'DELETE_POST_SUCCESS',
    DELETE_POST_FAILURE: 'DELETE_POST_FAILURE',
    // Like Post
    LIKE_POST_REQUEST: 'LIKE_POST_REQUEST',
    LIKE_POST_SUCCESS: 'LIKE_POST_SUCCESS',
    LIKE_POST_FAILURE: 'LIKE_POST_FAILURE',
    // Unlike Post
    UNLIKE_POST_REQUEST: 'UNLIKE_POST_REQUEST',
    UNLIKE_POST_SUCCESS: 'UNLIKE_POST_SUCCESS',
    UNLIKE_POST_FAILURE: 'UNLIKE_POST_FAILURE',
};