export const userConstants = {
    // Get User
    FETCH_USER_REQUEST: 'FETCH_USER_REQUEST',
    FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
    FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',
    // Delete User
    DELETE_USER: 'DELETE_USER',
    // Update User
    UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',
    // Follow User
    FOLLOW_USER_REQUEST: 'FOLLOW_USER_REQUEST',
    FOLLOW_USER_SUCCESS: 'FOLLOW_USER_SUCCESS',
    FOLLOW_USER_FAILURE: 'FOLLOW_USER_FAILURE',
    // UnFollow User
    UNFOLLOW_USER_REQUEST: 'UNFOLLOW_USER_REQUEST',
    UNFOLLOW_USER_SUCCESS: 'UNFOLLOW_USER_SUCCESS',
    UNFOLLOW_USER_FAILURE: 'UNFOLLOW_USER_FAILURE',

    // Find People
    FIND_PEOPLE_REQUEST: 'FIND_PEOPLE_REQUEST',
    FIND_PEOPLE_SUCCESS: 'FIND_PEOPLE_SUCCESS',
    FIND_PEOPLE_FAILURE: 'FIND_PEOPLE_FAILURE',
};