export const userConstants = {
    // Get User
    USER_REQUEST: 'USER_REQUEST',
    USER_SUCCESS: 'USER_SUCCESS',
    USER_FAILURE: 'USER_FAILURE',
    // Delete User
    DELETE_USER: 'DELETE_USER',
    // Update User
    UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',
    // Follow User
    FOLLOW_USER_REQUEST: 'FOLLOW_USER_REQUEST',
    FOLLOW_USER_SUCCESS: 'FOLLOW_USER_SUCCESS',
    FOLLOW_USER_FAILURE: 'FOLLOW_USER_FAILURE',
    // UnFollow User
    UNFOLLOW_USER_REQUEST: 'UNFOLLOW_USER_REQUEST',
    UNFOLLOW_USER_SUCCESS: 'UNFOLLOW_USER_SUCCESS',
    UNFOLLOW_USER_FAILURE: 'UNFOLLOW_USER_FAILURE',
};